name: Run RSpec tests
env:
  NAME: 'EcoATM Tiger Team'
on: [push]
jobs:
  build:
    env:
      JIRA_URL: ${{JIRA_URL}}
      TOKEN: ${{TOKEN}}
  run-rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 3.1.4
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run tests
        run: |
            bundle exec rspec