name: Run RSpec tests
env:
  NAME: 'EcoATM Tiger Team'
on: [push]
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    env:
      TOKEN = ${{ env.TOKEN }}
      JIRA = $ {{ env.JIRA }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 3.1.4
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run tests
        run: |
            bundle exec rspec